cache:
  - '%HOMEDRIVE%%HOMEPATH%\.gradle\caches'
  - '%HOMEDRIVE%%HOMEPATH%\.gradle\wrapper\dists'

build_script:
  - gradlew assemble

test_script:
  - gradlew check

after_test:
  - 7z a test-results.zip .\build\reports\tests\*

artifacts:
  - path: build\libs\*.jar
    name: Java library

# Deploy test result artifacts also for failed builds.
on_finish:
  - ps: Push-AppveyorArtifact test-results.zip -DeploymentName 'Test results'
